table Address
	lineageTag: a23f9ee2-22f9-4a22-b324-421fca5adb94

	column 'Tipo Entidad'
		dataType: int64
		formatString: 0
		lineageTag: fd4305ab-38cd-4f4e-aab6-96139850d361
		summarizeBy: sum
		sourceColumn: Tipo Entidad

		annotation SummarizationSetBy = Automatic

	column Entidad
		dataType: string
		lineageTag: f47cba6b-1cdc-4363-9599-7196505564d9
		summarizeBy: none
		sourceColumn: Entidad

		annotation SummarizationSetBy = Automatic

	column Direccion
		dataType: string
		lineageTag: ad44197f-2cb9-4893-8b5b-ae2cb2e1c861
		summarizeBy: none
		sourceColumn: Direccion

		annotation SummarizationSetBy = Automatic

	column Descripcion
		dataType: string
		lineageTag: 7c684196-29da-47e7-846e-4e80a8f86b8d
		summarizeBy: none
		sourceColumn: Descripcion

		annotation SummarizationSetBy = Automatic

	column 'Linea Direcion'
		dataType: string
		lineageTag: b235c005-3e7c-4b03-bf10-c8a53d984d9d
		dataCategory: Address
		summarizeBy: none
		sourceColumn: Linea Direcion

		annotation SummarizationSetBy = Automatic

	column 'Linea Direcion 1'
		dataType: string
		lineageTag: 285acd61-1c58-4d71-a600-fed05164e2a2
		summarizeBy: none
		sourceColumn: Linea Direcion 1

		annotation SummarizationSetBy = Automatic

	column 'Linea Direcion 2'
		dataType: string
		lineageTag: 017e736a-4f44-4fef-be43-e8a14dd6e414
		summarizeBy: none
		sourceColumn: Linea Direcion 2

		annotation SummarizationSetBy = Automatic

	column 'Codigo Postal'
		dataType: string
		lineageTag: 2ed74255-d9cf-4017-b339-fc4c00ec9e8a
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: Codigo Postal

		annotation SummarizationSetBy = Automatic

	column Ciudad
		dataType: string
		lineageTag: 0c46646b-612f-48e9-a281-1be9495b7942
		dataCategory: City
		summarizeBy: none
		sourceColumn: Ciudad

		annotation SummarizationSetBy = Automatic

	column Provincia
		dataType: string
		lineageTag: 42bd3245-8a95-4453-95b1-2c9037dd6cda
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: Provincia

		annotation SummarizationSetBy = Automatic

	column Pais
		dataType: string
		lineageTag: b581df8d-5a42-4391-ad00-8ab90448828b
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Pais

		annotation SummarizationSetBy = Automatic

	column País
		dataType: string
		lineageTag: 5a8eb72a-e39b-434f-8cc9-5b615502fdbe
		dataCategory: Country
		summarizeBy: none
		sourceColumn: País

		annotation SummarizationSetBy = Automatic

	column 'Telefono 1'
		dataType: string
		lineageTag: 214846a8-a63c-4bbf-a0fe-456276dc08c5
		summarizeBy: none
		sourceColumn: Telefono 1

		annotation SummarizationSetBy = Automatic

	column 'Telefono 2'
		dataType: string
		lineageTag: 70583f83-c69c-4b3e-85dc-82de6776b0d3
		summarizeBy: none
		sourceColumn: Telefono 2

		annotation SummarizationSetBy = Automatic

	column 'Telefono 3'
		dataType: string
		lineageTag: 3afd722f-7801-4b31-b5a2-4fe97af26d4b
		summarizeBy: none
		sourceColumn: Telefono 3

		annotation SummarizationSetBy = Automatic

	column 'Telefono 4'
		dataType: string
		lineageTag: d0511a5e-af7e-4575-8de4-5dec10bbae60
		summarizeBy: none
		sourceColumn: Telefono 4

		annotation SummarizationSetBy = Automatic

	column 'Telefono 5'
		dataType: string
		lineageTag: 7d5cede0-ce22-48b5-8aae-a0e7506993c5
		summarizeBy: none
		sourceColumn: Telefono 5

		annotation SummarizationSetBy = Automatic

	column Fax
		dataType: string
		lineageTag: 5aaf5188-cf64-462c-9a2c-52b56573d5b7
		summarizeBy: none
		sourceColumn: Fax

		annotation SummarizationSetBy = Automatic

	column Movil
		dataType: string
		lineageTag: cc8569c7-db18-4a7b-9663-cabc6eb3b3fa
		summarizeBy: none
		sourceColumn: Movil

		annotation SummarizationSetBy = Automatic

	column 'Correo 1'
		dataType: string
		lineageTag: 91839592-28fa-428b-a58f-dee9c6aecbc1
		summarizeBy: none
		sourceColumn: Correo 1

		annotation SummarizationSetBy = Automatic

	column 'Correo 2'
		dataType: string
		lineageTag: ef1a1aa1-4307-40f9-a267-b7f77d2f2711
		summarizeBy: none
		sourceColumn: Correo 2

		annotation SummarizationSetBy = Automatic

	column 'Correo 3'
		dataType: string
		lineageTag: 00256f58-b3f9-4d2b-a8ac-c689fc1ae52d
		summarizeBy: none
		sourceColumn: Correo 3

		annotation SummarizationSetBy = Automatic

	column 'Correo 4'
		dataType: string
		lineageTag: f9a222b9-f741-46e0-bc24-a9eb696e9bfa
		summarizeBy: none
		sourceColumn: Correo 4

		annotation SummarizationSetBy = Automatic

	column 'Correo 5'
		dataType: string
		lineageTag: 10e92098-7324-4468-8843-ce7d80057f99
		summarizeBy: none
		sourceColumn: Correo 5

		annotation SummarizationSetBy = Automatic

	column 'Sitio Web'
		dataType: string
		lineageTag: 6a3908ea-5114-4c30-8d27-2ebd5159e5a2
		summarizeBy: none
		sourceColumn: Sitio Web

		annotation SummarizationSetBy = Automatic

	column IdDireccion
		dataType: string
		lineageTag: 08de9ee7-7f48-4e82-8e52-351278fe3ae5
		summarizeBy: none
		sourceColumn: IdDireccion

		annotation SummarizationSetBy = Automatic

	column PaisCodigoPostal = 'Address'[Pais] & "-" & 'Address'[Codigo Postal]
		lineageTag: c0460151-0b7c-40be-83aa-1ea0c37c612c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Provincias.Provincias'
		dataType: string
		lineageTag: 71405aeb-cf82-4417-bdea-88ec89b63754
		summarizeBy: none
		sourceColumn: Provincias.Provincias

		annotation SummarizationSetBy = Automatic

	column 'Provincia Nombre'
		dataType: string
		lineageTag: 6bce2b71-42e8-4129-aec4-2f15544f1789
		summarizeBy: none
		sourceColumn: Provincia Nombre

		annotation SummarizationSetBy = Automatic

	column 'Provincia mapa' =
			-- 'Address'[Provincia Nombre]&", "&'Address'[País]
			'Address'[País] &", "&'Address'[Provincia Nombre]
		lineageTag: 627c3753-b518-4461-9350-8c99a5124869
		dataCategory: StateOrProvince
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Pais Jerarquía'
		lineageTag: 5ac7a66b-6fc9-42fc-ba4c-bf8841ab8932

		level Pais
			lineageTag: 3f3bde41-fb52-47b8-9eca-cb033fa5bcbb
			column: Pais

		level 'Codigo Postal'
			lineageTag: 575cdb59-fea8-4617-bf26-a572640e217e
			column: 'Codigo Postal'

		level Provincia
			lineageTag: 80310cbb-7436-4b1d-a7b9-78d0b5b5af14
			column: Provincia

		level Ciudad
			lineageTag: 2245c77d-9823-4286-a1ce-112eb0a4491b
			column: Ciudad

	hierarchy 'Nombre Pais Jerarquía'
		lineageTag: c6bd4074-f18a-4d92-9f1c-d93d1af75129

		level País
			lineageTag: 12e2e92f-f961-4972-8ce2-77fafc48232c
			column: País

		level Provincia
			lineageTag: 9b018f23-fd99-4ae0-ab5f-f1891786c01b
			column: Provincia

		level Ciudad
			lineageTag: 2acffd1d-4b7b-4348-938d-1410f86437b5
			column: Ciudad

		level 'Codigo Postal'
			lineageTag: 5799ecaf-223a-4b57-a36b-b5f91c2728fc
			column: 'Codigo Postal'

	partition Address-e18b7bd4-8a28-4423-a487-803742af1195 = m
		mode: import
		source = ```
				let
				    CurrentServer = Instancia,
				    CurrentDatabase = BaseDeDatos,
				    CurrentSchema = Esquema,
				    Origen = Sql.Database(CurrentServer, CurrentDatabase, [Query="
				                                                                SELECT  
				          [BPATYP_0]
				         ,[BPANUM_0]
				         ,[BPAADD_0]
				         ,[BPADES_0]
				         ,[BPAADDLIG_0]
				         ,[BPAADDLIG_1]
				         ,[BPAADDLIG_2]
				         ,[POSCOD_0]
				         ,[CTY_0]
				         ,[SAT_0]
				         ,ADR.[CRY_0]
				         ,[CRYNAM_0]
				         ,[TEL_0]
				         ,[TEL_1]
				         ,[TEL_2]
				         ,[TEL_3]
				         ,[TEL_4]
				         ,[FAX_0]
				         ,[MOB_0]
				         ,[WEB_0]
				         ,[WEB_1]
				         ,[WEB_2]
				         ,[WEB_3]
				         ,[WEB_4]
				         ,[FCYWEB_0]
						 ,AXX.TEXTE_0
				 FROM " & CurrentSchema & ".BPADDRESS ADR 
				 left join " & CurrentSchema & ".TABSUBDIV TSD on TSD.CRY_0=ADR.CRY_0 and ADR.SAT_0=TSD.COD_0 and TSD.TYP_0 = 3
				 left join " & CurrentSchema & ".ATEXTRA AXX on (AXX.CODFIC_0 = 'TABSUBDIV' and AXX.ZONE_0 = 'INTIT' and AXX.LANGUE_0 = 'SPA' and AXX.IDENT1_0 = TSD.CRYTYP_0 and AXX.IDENT2_0 = TSD.COD_0)"
				                                                          ]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(Origen,{{"BPATYP_0", "Tipo Entidad"}, {"BPANUM_0", "Entidad"}, {"BPAADD_0", "Direccion"}, {"BPADES_0", "Descripcion"}, {"BPAADDLIG_0", "Linea Direcion"}, {"BPAADDLIG_1", "Linea Direcion 1"}, {"BPAADDLIG_2", "Linea Direcion 2"}, {"POSCOD_0", "Codigo Postal"}, {"CTY_0", "Ciudad"}, {"SAT_0", "Provincia"}, {"CRY_0", "Pais"}, {"CRYNAM_0", "Nombre Pais"}, {"TEL_0", "Telefono 1"}, {"TEL_1", "Telefono 2"}, {"TEL_2", "Telefono 3"}, {"TEL_3", "Telefono 4"}, {"TEL_4", "Telefono 5"}, {"FAX_0", "Fax"}, {"MOB_0", "Movil"}, {"WEB_0", "Correo 1"}, {"WEB_1", "Correo 2"}, {"WEB_2", "Correo 3"}, {"WEB_3", "Correo 4"}, {"WEB_4", "Correo 5"}, {"FCYWEB_0", "Sitio Web"},{"TEXTE_0", "Provincia Nombre"}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "IdDireccion", each [Entidad]&"-"&[Direccion]),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Personalizada agregada",{"IdDireccion", "Tipo Entidad", "Entidad", "Direccion", "Descripcion", "Linea Direcion", "Linea Direcion 1", "Linea Direcion 2", "Codigo Postal", "Ciudad", "Provincia", "Pais", "Nombre Pais", "Telefono 1", "Telefono 2", "Telefono 3", "Telefono 4", "Telefono 5", "Fax", "Movil", "Correo 1", "Correo 2", "Correo 3", "Correo 4", "Correo 5", "Sitio Web"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Columnas reordenadas",{{"Nombre Pais", "País"}}),
				    #"Merged Queries" = Table.FuzzyNestedJoin(#"Renamed Columns", {"Provincia"}, Provincias, {"Provincias"}, "Provincias", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true, Threshold=0.6]),
				    #"Expanded Provincias" = Table.ExpandTableColumn(#"Merged Queries", "Provincias", {"Provincias"}, {"Provincias.Provincias"}),
				    #"Uppercased Text" = Table.TransformColumns(#"Expanded Provincias",{{"Provincia", Text.Upper, type text}, {"Ciudad", Text.Upper, type text}}),
				    #"Valor Cordoba" = Table.ReplaceValue(#"Uppercased Text","Córdoba","Córdoba, Andalucia",Replacer.ReplaceText,{"Provincia Nombre"}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Valor Cordoba","Granada","Granada, Andalucia",Replacer.ReplaceText,{"Provincia Nombre"}),
				    #"Valor Zaragoza" = Table.ReplaceValue(#"Valor reemplazado","Zaragoza","Zaragoza, Aragón",Replacer.ReplaceText,{"Provincia Nombre"}),
				    #"Valor Toledo" = Table.ReplaceValue(#"Valor Zaragoza","Toledo","Toledo, Castilla-La Mancha",Replacer.ReplaceText,{"Provincia Nombre"}),
				    #"Valor Las Palmas" = Table.ReplaceValue(#"Valor Toledo","Palmas, Las","Las Palmas",Replacer.ReplaceText,{"Provincia Nombre"}),
				    #"Valor La Rioja" = Table.ReplaceValue(#"Valor Las Palmas","Rioja, La","La Rioja",Replacer.ReplaceText,{"Provincia Nombre"})
				in
				    #"Valor La Rioja"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

