table Company
	lineageTag: 008568a0-5739-43d3-909e-27205a3c0d29

	column Empresa
		dataType: string
		lineageTag: 58846c99-fe58-429d-9510-f4578c180b5b
		summarizeBy: none
		sourceColumn: Empresa

		annotation SummarizationSetBy = Automatic

	column 'Nombre Empresa'
		dataType: string
		lineageTag: 80090e9b-6f29-4c3b-9966-1ac23ce4e165
		summarizeBy: none
		sourceColumn: Nombre Empresa

		annotation SummarizationSetBy = Automatic

	column 'Sociedad Juridica'
		dataType: int64
		formatString: 0
		lineageTag: 2f48e1a4-007b-4694-a17c-31b2244b2491
		summarizeBy: none
		sourceColumn: Sociedad Juridica

		annotation SummarizationSetBy = Automatic

	column Legislacion
		dataType: string
		lineageTag: 8896f65b-d726-4040-abba-d21131c116ac
		summarizeBy: none
		sourceColumn: Legislacion

		annotation SummarizationSetBy = Automatic

	column 'Modelo Contable'
		dataType: string
		lineageTag: d64a3af1-e4c8-4909-bfa5-685868962d7f
		summarizeBy: none
		sourceColumn: Modelo Contable

		annotation SummarizationSetBy = Automatic

	column 'Planta Principal'
		dataType: string
		lineageTag: 290e54ee-5418-4362-986a-06d8fca6c63e
		summarizeBy: none
		sourceColumn: Planta Principal

		annotation SummarizationSetBy = Automatic

	column Pais
		dataType: string
		lineageTag: f8163480-5d6a-497f-9e52-655d7e3d12b0
		summarizeBy: none
		sourceColumn: Pais

		annotation SummarizationSetBy = Automatic

	column Direccion
		dataType: string
		lineageTag: 67533869-4361-43d6-bb2b-3bb4f7627413
		summarizeBy: none
		sourceColumn: Direccion

		annotation SummarizationSetBy = Automatic

	column IdDireccion
		dataType: string
		lineageTag: d538f7d2-4989-49f9-b47b-10f1ce98dbd3
		summarizeBy: none
		sourceColumn: IdDireccion

		annotation SummarizationSetBy = Automatic

	partition Company-30c7b845-79ce-417a-a075-ef408ab4a039 = m
		mode: import
		source = ```
				let
				    CurrentServer = Instancia,
				    CurrentDatabase = BaseDeDatos,
				    CurrentSchema = Esquema,
				    Origen = Sql.Database(CurrentServer, CurrentDatabase, [Query="
				                                                                SELECT  
				                                                                     [CPY_0]
				                                                                    ,[CPYNAM_0]
				                                                                    ,[BPAADD_0]
				                                                                    ,[CPYLEGFLG_0]
				                                                                    ,[LEG_0]
				                                                                    ,[ACM_0]
				                                                                    ,[MAIFCY_0]
				                                                                    ,[CRY_0]   
				                                                                FROM " & CurrentSchema & ".COMPANY"
				                                                          ]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(Origen,{{"CPY_0", "Empresa"}, {"CPYNAM_0", "Nombre Empresa"}, {"CPYLEGFLG_0", "Sociedad Juridica"}, {"LEG_0", "Legislacion"}, {"ACM_0", "Modelo Contable"}, {"MAIFCY_0", "Planta Principal"}, {"CRY_0", "Pais"}, {"BPAADD_0", "Direccion"}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "IdDireccion", each [Empresa]&"-"&[Direccion]),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Personalizada agregada",{"IdDireccion", "Empresa", "Nombre Empresa", "Direccion", "Sociedad Juridica", "Legislacion", "Modelo Contable", "Planta Principal", "Pais"})
				in
				    #"Columnas reordenadas"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

