table Customer
	lineageTag: 87a08bef-d5ce-488c-843d-139538bde7f0

	column IdCliente
		dataType: string
		lineageTag: 194e73c1-64c3-4f1b-9d47-9845019f04b5
		summarizeBy: none
		sourceColumn: IdCliente

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: string
		lineageTag: 756195ea-7201-4235-92a7-32be03b94b21
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 588b3f22-0580-4a91-bd9c-e1617193c8b3
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Grupo
		dataType: string
		lineageTag: b992a0be-7592-4a2f-9966-aa4e48dc1e5a
		summarizeBy: none
		sourceColumn: Grupo

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: int64
		formatString: 0
		lineageTag: eed2a143-579a-42a6-ab87-308f8bdbee3f
		summarizeBy: sum
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Direccion
		dataType: string
		lineageTag: 83115311-0da2-4fe5-ab52-201298935e9b
		summarizeBy: none
		sourceColumn: Direccion

		annotation SummarizationSetBy = Automatic

	column Moneda
		dataType: string
		lineageTag: f52764c3-2344-4dc5-b3d4-c7ebe2108a58
		summarizeBy: none
		sourceColumn: Moneda

		annotation SummarizationSetBy = Automatic

	column IdDireccion
		dataType: string
		lineageTag: 8f085392-8d0e-45f0-b595-c968aa6b81f7
		summarizeBy: none
		sourceColumn: IdDireccion

		annotation SummarizationSetBy = Automatic

	column Pais
		dataType: string
		lineageTag: 57c32dad-77ae-4c88-8e89-126051d1b192
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Pais

		annotation SummarizationSetBy = Automatic

	column Ciudad
		dataType: string
		lineageTag: b798c055-1eac-41ec-98dd-38403857c68e
		dataCategory: City
		summarizeBy: none
		sourceColumn: Ciudad

		annotation SummarizationSetBy = Automatic

	column Ciudad-Pais = [Ciudad] & ", " & [Pais]
		lineageTag: ebceaea8-f40f-4be6-87b2-28bad816da1d
		dataCategory: Country
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Inf Moneda' = """" &  'Customer'[Moneda] & """"
		isHidden
		lineageTag: 10f6eff3-ce96-47d8-8770-7dafcfdb237d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'IdDireccion Jerarquía'
		lineageTag: 7f194bf5-bb74-418c-98f2-f303e4718619

		level IdDireccion
			lineageTag: 7cfded6a-281a-4221-a964-bb0731a4ab75
			column: IdDireccion

		level Pais
			lineageTag: 2c335717-c919-41b8-aa7b-de58ec1d1919
			column: Pais

	hierarchy 'Grupo Jerarquía'
		lineageTag: 7bb38e0f-04da-4255-8ae3-c6fae2621d0e

		level Grupo
			lineageTag: c7f3868f-3405-40b3-b416-54aea3793b36
			column: Grupo

		level Cliente
			lineageTag: 8f7757c8-ec6e-4ecd-a0f0-581a7905fba3
			column: Cliente

	partition Customer-53a8d1e2-fa5d-4c94-b706-9994f227b7f6 = m
		mode: import
		source = ```
				let
				    CurrentServer = Instancia,
				    CurrentDatabase = BaseDeDatos,
				    CurrentSchema = Esquema,
				    Origen = Sql.Database(CurrentServer, CurrentDatabase, [Query="
				                                                                SELECT  
				                                                                     c.[BPCNUM_0]
				                                                                    ,c.[BPCNAM_0]
				                                                                    ,c.[BCGCOD_0]
				                                                                    ,c.[GRP_0]
				                                                                    ,c.[BPCTYP_0]
				                                                                    ,c.[BPAINV_0]
				                                                                    ,c.[CUR_0]
				                                                                    ,a.CRY_0
				                                                                    ,a.CTY_0
				                                                                FROM " & CurrentSchema & ".BPCUSTOMER as c
				                                                                LEFT JOIN " & CurrentSchema & ".BPADDRESS as a
				                                                                on c.BPCNUM_0 = a.BPANUM_0 and c.BPAINV_0 = a.BPAADD_0 and c.BPCTYP_0 = a.BPATYP_0" 
				                                                          ]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(Origen,{{"BPCNUM_0", "IdCliente"}, {"BPCNAM_0", "Cliente"}, {"BCGCOD_0", "Categoria"}, {"GRP_0", "Grupo"}, {"BPCTYP_0", "Tipo"}, {"BPAINV_0", "Direccion"}, {"CUR_0", "Moneda"}, {"CRY_0", "Pais"}, {"CTY_0", "Ciudad"}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "IdDireccion", each [IdCliente] & "-" & [Direccion])
				in
				    #"Personalizada agregada"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

