table DocumentosCabecera
	lineageTag: 2c2adf06-bfe9-4db6-863b-539ade518b35

	column 'Tipo Factura'
		dataType: string
		lineageTag: a703b272-0aa7-4702-a9b4-7e2666cb514f
		summarizeBy: none
		sourceColumn: Tipo Factura

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: string
		lineageTag: e5c0761a-767a-49c8-9a87-a6ba0a93c0b8
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column Empresa
		dataType: string
		lineageTag: 67605316-e089-42d9-9b36-1e1161bc0ba3
		summarizeBy: none
		sourceColumn: Empresa

		annotation SummarizationSetBy = Automatic

	column Moneda
		dataType: string
		lineageTag: 2e0f0645-cff0-4f76-a6e7-1ed07b101342
		summarizeBy: none
		sourceColumn: Moneda

		annotation SummarizationSetBy = Automatic

	column Descuento
		dataType: string
		lineageTag: cf9eb6a0-a974-4db4-b7d3-bcaa4521bee8
		summarizeBy: none
		sourceColumn: Descuento

		annotation SummarizationSetBy = Automatic

	column 'Planta Venta'
		dataType: string
		lineageTag: f4858cf6-ace4-43e3-a3b2-38098f4d121d
		summarizeBy: none
		sourceColumn: Planta Venta

		annotation SummarizationSetBy = Automatic

	column IdCliente
		dataType: string
		lineageTag: 8f007af8-2c49-4a6e-a8c5-6917a97a3772
		summarizeBy: none
		sourceColumn: IdCliente

		annotation SummarizationSetBy = Automatic

	column 'Fecha Factura'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 101b710f-253d-4238-9f51-c0cccbff3129
		summarizeBy: none
		sourceColumn: Fecha Factura

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Ratio Descuento'
		dataType: double
		lineageTag: d96cb99f-8df2-4fe9-8543-840c6aed8b10
		summarizeBy: sum
		sourceColumn: Ratio Descuento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Validacion
		dataType: int64
		formatString: 0
		lineageTag: 6901deac-c953-48b6-8e79-6704b504d112
		summarizeBy: sum
		sourceColumn: Validacion

		annotation SummarizationSetBy = Automatic

	column 'Regimen Tercero'
		dataType: string
		lineageTag: 50ada86e-f4fc-4b2d-94fb-5171bd2b9a32
		summarizeBy: none
		sourceColumn: Regimen Tercero

		annotation SummarizationSetBy = Automatic

	column Modulo
		dataType: int64
		formatString: 0
		lineageTag: 225b07b4-bad1-4c0f-8f1a-6bb9c1f1dfc0
		summarizeBy: sum
		sourceColumn: Modulo

		annotation SummarizationSetBy = Automatic

	column Year_Factura = YEAR('DocumentosCabecera'[Fecha Factura])
		formatString: 0
		lineageTag: 90f57f8e-d4cf-44c7-b57b-29522f6b1361
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition DocumentosCabecera-3e3cbdec-8425-4757-aa6f-5f74f0d0ac2b = m
		mode: import
		source = ```
				let
				    CurrentServer = Instancia,
				    CurrentDatabase = BaseDeDatos,
				    CurrentSchema = Esquema,
				    CurrentRows = Registros,
				    CurrentPeriod = Periodo,
				    Origen = Sql.Database(CurrentServer, CurrentDatabase, [Query="
				
				DECLARE @ANO1 VARCHAR(20)
				DECLARE @ANO2 int
				set @ANO1='"& CurrentPeriod &"'
				set @ANO2=(SELECT MIN(PERIODO) FROM (	SELECT YEAR(ACCDAT_0) AS PERIODO,COUNT(*) AS REGISTROS,
														SUM(COUNT(*)) OVER (ORDER BY YEAR(ACCDAT_0) DESC) AS ACUMULADO
														FROM " & CurrentSchema &".SINVOICED as SED left join " & CurrentSchema &".SINVOICE AS SE on SED.NUM_0 = SE.NUM_0
														where SE.ORIMOD_0=5 and INVTYP_0 <>5 
														GROUP BY YEAR(ACCDAT_0)
														) A	WHERE ACUMULADO <=" & CurrentRows &")
														
				
				IF @ANO1='Periodo automático'
				
				(
				            SELECT
				            [NUM_0],
				            [CPY_0],
				            [FCY_0]
				            ,[BPR_0]
				            ,[SIVTYP_0]     
				            ,[ACCDAT_0]
				            ,[CUR_0]
				            ,[DEP_0]
				            ,[DEPRAT_0]
				            ,[STA_0]
				            ,[VAC_0]
				            ,[ORIMOD_0]
				            FROM " & CurrentSchema & ".SINVOICE
				            WHERE [ORIMOD_0] = 5  and INVTYP_0 in (1,2) AND YEAR(ACCDAT_0)>=@ANO2
				
				)
				
				            ELSE
				
				(
				            SELECT
				            [NUM_0],
				            [CPY_0],
				            [FCY_0]
				            ,[BPR_0]
				            ,[SIVTYP_0]     
				            ,[ACCDAT_0]
				            ,[CUR_0]
				            ,[DEP_0]
				            ,[DEPRAT_0]
				            ,[STA_0]
				            ,[VAC_0]
				            ,[ORIMOD_0]
				            FROM " & CurrentSchema & ".SINVOICE
				            WHERE [ORIMOD_0] = 5  and INVTYP_0 in (1,2) AND YEAR(ACCDAT_0)>=@ANO1
				 )
				
				    "
				]),
				
				    #"Columnas con nombre cambiado" = Table.RenameColumns(Origen,{{"NUM_0", "Documento"}, {"CPY_0", "Empresa"}, {"FCY_0", "Planta Venta"}, {"BPR_0", "IdCliente"}, {"SIVTYP_0", "Tipo Factura"}, {"ACCDAT_0", "Fecha Factura"}, {"CUR_0", "Moneda"}, {"DEP_0", "Descuento"}, {"DEPRAT_0", "Ratio Descuento"}, {"STA_0", "Validacion"}, {"VAC_0", "Regimen Tercero"}, {"ORIMOD_0", "Modulo"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Columnas con nombre cambiado", each true)
				in
				    #"Filtered Rows"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

