table Item
	lineageTag: 8099d0dd-b23d-43ec-b6cc-fa03fb491aaa

	column IdItem
		dataType: string
		lineageTag: 132bcd5e-18e2-4703-a97c-a5b366be991b
		summarizeBy: none
		sourceColumn: IdItem

		annotation SummarizationSetBy = Automatic

	column Sociedad
		dataType: string
		lineageTag: f3325be6-ab4c-4146-953f-0104ec962be3
		summarizeBy: none
		sourceColumn: Sociedad

		annotation SummarizationSetBy = Automatic

	column IdCategoria
		dataType: string
		lineageTag: e2610429-f116-4521-be63-e1773eb3cd50
		summarizeBy: none
		sourceColumn: IdCategoria

		annotation SummarizationSetBy = Automatic

	column CATEGORIA
		dataType: string
		lineageTag: ff9e279b-6ccb-47e2-a5e4-80d3be11fc83
		summarizeBy: none
		sourceColumn: CATEGORIA

		annotation SummarizationSetBy = Automatic

	column 'Codigo Contable'
		dataType: string
		lineageTag: 57d86ce7-407f-4c41-9017-697edbed8baa
		summarizeBy: none
		sourceColumn: Codigo Contable

		annotation SummarizationSetBy = Automatic

	column 'Descripcion 1'
		dataType: string
		lineageTag: 0619b831-7421-4468-8fc1-a4c22387e76e
		summarizeBy: none
		sourceColumn: Descripcion 1

		annotation SummarizationSetBy = Automatic

	column 'Descripcion 2'
		dataType: string
		lineageTag: 95404757-1387-4983-bd1c-07eb3205b663
		summarizeBy: none
		sourceColumn: Descripcion 2

		annotation SummarizationSetBy = Automatic

	column 'Descripcion 3'
		dataType: string
		lineageTag: bf3751f2-6035-45fc-8f15-58236972e334
		summarizeBy: none
		sourceColumn: Descripcion 3

		annotation SummarizationSetBy = Automatic

	column Unidad
		dataType: string
		lineageTag: 24bede8b-cee0-449a-960f-a2621385d03f
		summarizeBy: none
		sourceColumn: Unidad

		annotation SummarizationSetBy = Automatic

	column 'Nivel Impuesto'
		dataType: string
		lineageTag: 56672e1d-cd17-4566-ba26-8a8ca7fe3321
		summarizeBy: none
		sourceColumn: Nivel Impuesto

		annotation SummarizationSetBy = Automatic

	column Comprador
		dataType: string
		lineageTag: d7481652-4928-438f-bcd8-ce89a0fcd1ce
		summarizeBy: none
		sourceColumn: Comprador

		annotation SummarizationSetBy = Automatic

	column 'Precio Base'
		dataType: double
		lineageTag: d47459b2-2841-4df1-ac2f-89130ff6a741
		summarizeBy: sum
		sourceColumn: Precio Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Coef Gastos Entrega'
		dataType: double
		lineageTag: b203bc43-bfdf-4e3c-871e-0b263b6575a1
		summarizeBy: sum
		sourceColumn: Coef Gastos Entrega

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Coste Fijo Unitario'
		dataType: double
		lineageTag: dc404985-d757-451a-b602-2a32645be963
		summarizeBy: sum
		sourceColumn: Coste Fijo Unitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Codigo Business Unit Analisis'
		dataType: string
		lineageTag: e14f52d5-4d20-4964-8891-db1a94181598
		summarizeBy: none
		sourceColumn: Codigo Business Unit Analisis

		annotation SummarizationSetBy = Automatic

	column 'Codigo Familia Analisis'
		dataType: string
		lineageTag: 2987f899-69a3-4b4f-9cd4-84ee27eb259e
		summarizeBy: none
		sourceColumn: Codigo Familia Analisis

		annotation SummarizationSetBy = Automatic

	column 'Business Unit'
		dataType: string
		lineageTag: 7921d200-35c9-4013-91e6-aea436f79beb
		summarizeBy: none
		sourceColumn: Business Unit

		annotation SummarizationSetBy = Automatic

	column Familia
		dataType: string
		lineageTag: a049e3f4-e63f-43f2-8ae2-d1ea9ea2da2d
		summarizeBy: none
		sourceColumn: Familia

		annotation SummarizationSetBy = Automatic

	column 'Cantidad Minima'
		dataType: double
		lineageTag: 97bf05f7-1e17-432e-a299-d5fe04eb927e
		summarizeBy: sum
		sourceColumn: Cantidad Minima

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cantidad Máxima'
		dataType: double
		lineageTag: f7c61c3e-4a82-499f-a98d-863339f6d018
		summarizeBy: sum
		sourceColumn: Cantidad Máxima

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Margen Minimo'
		dataType: double
		lineageTag: 69c8342e-8652-41a0-a281-1d25924f5088
		summarizeBy: sum
		sourceColumn: Margen Minimo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Precio Minimo'
		dataType: double
		lineageTag: 50618ef2-21de-4b06-b54e-43760614f776
		summarizeBy: sum
		sourceColumn: Precio Minimo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Precio Teorico'
		dataType: double
		lineageTag: 19ac4dfa-058a-4993-885b-daba1af821d5
		summarizeBy: sum
		sourceColumn: Precio Teorico

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Precio Base Ventas'
		dataType: double
		lineageTag: d3e1aa88-2300-41ed-a6e1-b4fab83cb03a
		summarizeBy: sum
		sourceColumn: Precio Base Ventas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Eje Analitico 1'
		dataType: string
		lineageTag: fd363a45-3b8e-4433-b03b-9f12adee820f
		summarizeBy: none
		sourceColumn: Eje Analitico 1

		annotation SummarizationSetBy = Automatic

	column 'Eje Analitico 2'
		dataType: string
		lineageTag: 4cad8cbd-3647-4a44-aef8-11b0946e17fa
		summarizeBy: none
		sourceColumn: Eje Analitico 2

		annotation SummarizationSetBy = Automatic

	column 'Eje Analitico 3'
		dataType: string
		lineageTag: 02f7573f-ee01-41e9-ba0e-06303758685b
		summarizeBy: none
		sourceColumn: Eje Analitico 3

		annotation SummarizationSetBy = Automatic

	column 'Eje Analitico 4'
		dataType: string
		lineageTag: d2aa775f-63a0-4542-9df0-73b35be09f6f
		summarizeBy: none
		sourceColumn: Eje Analitico 4

		annotation SummarizationSetBy = Automatic

	column IdArticulo_descripcion = CONCATENATE('Item'[IdItem],CONCATENATE(" - ",'Item'[Descripcion 1]))
		lineageTag: e5c633d7-2210-4fcc-bd6e-be50ca28f868
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Supplier
		dataType: string
		lineageTag: f279ed9e-2835-40c4-8dff-d507306f0287
		summarizeBy: none
		sourceColumn: Supplier

		annotation SummarizationSetBy = Automatic

	column 'Vygon Item Number'
		dataType: string
		lineageTag: aafb25a3-1135-4743-9455-a05295b06225
		summarizeBy: none
		sourceColumn: Vygon Item Number

		annotation SummarizationSetBy = Automatic

	column 'Subsidiary ID'
		dataType: string
		lineageTag: 83c5b6c4-2d3c-462b-b991-0ebd817c180a
		summarizeBy: none
		sourceColumn: Subsidiary ID

		annotation SummarizationSetBy = Automatic

	column EOR
		dataType: string
		lineageTag: 3f236d93-e01e-4666-9797-75c9f4dc38cd
		summarizeBy: none
		sourceColumn: EOR

		annotation SummarizationSetBy = Automatic

	column 'Purchased from VYGON'
		dataType: string
		lineageTag: 10b204f7-75d7-4ab8-8951-aa14c0202f45
		summarizeBy: none
		sourceColumn: Purchased from VYGON

		annotation SummarizationSetBy = Automatic

	column 'Inf IdItem' = "'" &  'Item'[IdItem] & "'"
		isHidden
		lineageTag: 0c06e773-e4f6-4bd4-88b6-47fd69ea396b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Inf Descripcion' = """" &  'Item'[Descripcion 1] & """"
		isHidden
		lineageTag: 343fee97-a524-4e75-b8d4-56ffc6a5cf43
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Inf Purchased from VYGON' = """" &  'Item'[Purchased from VYGON] & """"
		isHidden
		lineageTag: 5f5ca1e1-8eef-4031-b36c-8a0b2ed14586
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Inf Supplier' = """" &  'Item'[Supplier] & """"
		isHidden
		lineageTag: 8f3762b5-4326-4c1a-b6cf-5ab33e31b7d9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Inf Vygon Item Number' = """" &  'Item'[Vygon Item Number] & """"
		isHidden
		lineageTag: 94d4424b-739f-460b-a64e-1c4c92bcccf3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Item-23e52532-cf86-420a-9324-3147ff6164b4 = m
		mode: import
		source =
				let
				    CurrentServer = Instancia,
				    CurrentDatabase = BaseDeDatos,
				    CurrentSchema = Esquema,
				    CurrentCompany = Empresa,
				    Origen = Sql.Database(CurrentServer, CurrentDatabase, [Query="
				                                                                SELECT   ITM.[ITMREF_0] AS IdItem
				                                                                        ,ITM.[CPY_0] AS Sociedad
				                                                                        ,ITM.[TCLCOD_0] AS IdCategoria
				                                                                        ,TXCAT.TEXTE_0 AS CATEGORIA
				                                                                        ,ITM.[ACCCOD_0] AS 'Codigo Contable'
				                                                                        ,ITM.[ITMDES1_0] AS 'Descripcion 1'
				                                                                        ,ITM.[ITMDES2_0] AS 'Descripcion 2'
				                                                                        ,ITM.[ITMDES3_0] AS 'Descripcion 3'
				                                                                        ,ITM.[STU_0] AS Unidad
				                                                                        ,ITM.[VACITM_0] AS 'Nivel Impuesto'
				                                                                        ,ITM.[BUY_0] AS Comprador
				                                                                        ,ITM.[PURBASPRI_0] AS 'Precio Base'
				                                                                        ,ITM.[CPRCOE_0] AS 'Coef Gastos Entrega'
				                                                                        ,ITM.[CPRAMT_0] AS 'Coste Fijo Unitario'
				                                                                        ,ITM.[CCE_0] AS 'Eje Analitico 1'
				                                                                        ,ITM.[CCE_1] AS 'Eje Analitico 2'
				                                                                        ,ITM.[CCE_2] AS 'Eje Analitico 3'
				                                                                        ,ITM.[CCE_3] AS 'Eje Analitico 4'
				                                                                        ,ITM.TSICOD_0 AS 'Codigo Famlia Analisis'
				                                                                        ,ITM.TSICOD_1 AS 'Codigo Subfamilia Analisis'
				                                                                        ,TXT.TEXTE_0 AS Familia
				                                                                        ,TXT2.TEXTE_0 AS Subfamilia
				                                                                        ,ITMS.[MINQTY_0] AS 'Cantidad Minima'
				                                                                        ,ITMS.[MAXQTY_0] AS 'Cantidad Máxima'
				                                                                        ,ITMS.[MINPFM_0] AS 'Margen Minimo'
				                                                                        ,ITMS.[MINPRI_0] AS 'Precio Minimo'
				                                                                        ,ITMS.[THEPRI_0] AS 'Precio Teorico'
				                                                                        ,ITMS.[BASPRI_0] AS 'Precio Base Ventas'
																						,(select top 1 ITS.BPSNUM_0 from " & CurrentSchema & ".ITMBPS ITS where ITS.ITMREF_0 = ITM.ITMREF_0 and ITS.PIO_0 = 0) as Supplier
																						,(select top 1 ITS.ITMREFBPS_0 from " & CurrentSchema & ".ITMBPS ITS where ITS.ITMREF_0 = ITM.ITMREF_0 and ITS.BPSNUM_0='" & CurrentCompany &"') as [Vygon Item Number]
																						,case when BPS.ITMREF_0 is null then 'N' else 'Y' end as 'Purchased from VYGON'
				                                                                    FROM " & CurrentSchema & ".ITMMASTER AS ITM
				                                                                    LEFT JOIN " & CurrentSchema & ".[ITMSALES] AS ITMS
				                                                                    ON ITM.ITMREF_0 = ITMS.ITMREF_0
				                                                                    LEFT JOIN " & CurrentSchema & ".ATEXTRA as TXT
				                                                                    on ITM.TSICOD_0 = TXT.IDENT2_0  AND CODFIC_0 = 'ATABDIV' AND ZONE_0 = 'LNGDES' AND IDENT1_0 = '20' AND LANGUE_0 = 'SPA'
				                                                                    LEFT JOIN " & CurrentSchema & ".ATEXTRA as TXT2
				                                                                    on ITM.TSICOD_1 = TXT2.IDENT2_0 AND TXT2.CODFIC_0 = 'ATABDIV' AND TXT2.ZONE_0 = 'LNGDES' AND TXT2.IDENT1_0 = '21' AND TXT2.LANGUE_0 = 'SPA'
				                                                                    LEFT JOIN " & CurrentSchema & ".ATEXTRA AS TXCAT
				                                                                    ON ITM.TCLCOD_0 = TXCAT.IDENT1_0 AND TXCAT.CODFIC_0 = 'ITMCATEG' AND TXCAT.ZONE_0 = 'TCLAXX' AND TXCAT.LANGUE_0 = 'SPA'
																					LEFT JOIN  PROTO.ITMBPS BPS on ITM.ITMREF_0=BPS.ITMREF_0  and BPS.BPSNUM_0='" & CurrentCompany &"'"
				                                                          ]),
				    #"Added Custom" = Table.AddColumn(Origen, "Subsidiary ID", each "ES"),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "EOR", each "EOR"),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom1",{{"Familia", "Business Unit"}, {"Codigo Famlia Analisis", "Codigo Business Unit Analisis"}, {"Codigo Subfamilia Analisis", "Codigo Familia Analisis"}, {"Subfamilia", "Familia"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

