table Price
	lineageTag: 234d2824-c1e0-421d-84ee-017b0d8e4fef

	column 'Estructura Tarifa'
		dataType: string
		lineageTag: da0bce74-6b71-43c8-8c9a-366c6f15edb2
		summarizeBy: none
		sourceColumn: Estructura Tarifa

		annotation SummarizationSetBy = Automatic

	column 'Cod tarifa'
		dataType: string
		lineageTag: c8ea8fd6-49cb-4280-8e66-0e73ac935171
		summarizeBy: none
		sourceColumn: Cod tarifa

		annotation SummarizationSetBy = Automatic

	column 'Fecha inicio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e9325e36-4ce3-487e-8022-3d59ea3df834
		summarizeBy: none
		sourceColumn: Fecha inicio

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fecha fin'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b8b07610-36a1-4edb-b1f0-1b7ed7d594aa
		summarizeBy: none
		sourceColumn: Fecha fin

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IdArticulo
		dataType: string
		lineageTag: d21c5e21-5d9e-406e-9dd5-f54587d16747
		summarizeBy: none
		sourceColumn: IdArticulo

		annotation SummarizationSetBy = Automatic

	column IdProveedor
		dataType: string
		lineageTag: 683a4530-cf9f-4bba-b58c-79ea8c572307
		summarizeBy: none
		sourceColumn: IdProveedor

		annotation SummarizationSetBy = Automatic

	column 'Precio compra'
		dataType: double
		lineageTag: d02ae60d-d93d-4d75-be58-b3b3b0b4f39d
		summarizeBy: sum
		sourceColumn: Precio compra

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Dto1
		dataType: double
		lineageTag: 0e2a2a88-2acd-416c-8069-9afe7d28962b
		summarizeBy: sum
		sourceColumn: Dto1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Dto2
		dataType: double
		lineageTag: a7fcf274-1e54-4344-9847-5558f1b101b8
		summarizeBy: sum
		sourceColumn: Dto2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Price-ef8847b0-eb7f-43d1-8846-9c2c311a5bee = m
		mode: import
		source = ```
				let
				    CurrentServer = Instancia,
				    CurrentDatabase = BaseDeDatos,
				    CurrentSchema = Esquema,
				    CurrentRows = Registros,
				    CurrentPeriod = Periodo,
				    Origen = Sql.Database(CurrentServer, CurrentDatabase, [Query="
				                                                            SELECT PLI_0 'Estructura Tarifa', 
				                                                            PLICRD_0 'Cod tarifa', 
				                                                            PLISTRDAT_0 'Fecha inicio', 
				                                                            PLIENDDAT_0 'Fecha fin', 
				                                                            PLICRI1_0 'IdArticulo', 
				                                                            PLICRI2_0 'IdProveedor', 
				                                                            PRI_0 'Precio compra', 
				                                                            DCGVAL_0 'Dto1', 
				                                                            DCGVAL_1 'Dto2'
				                                                            FROM " & CurrentSchema & ".PPRICLIST 
				                                                            WHERE PLI_0 = 'T001'
				                                                            AND PLISTRDAT_0 <= GETDATE()
				                                                            AND PLIENDDAT_0 >= GETDATE()
				                                                        "]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Fecha inicio", type date}, {"Fecha fin", type date}})
				in
				    #"Tipo cambiado"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

