table 'Sales Invoice Line'
	lineageTag: 821da74c-f6eb-4554-8a9d-531618a48278

	column Year_Factura = YEAR('Sales Invoice Line'[Fecha Factura])
		formatString: 0
		lineageTag: 2901d560-a3d1-4ce4-a192-b1f2f9a26564
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Id_Fecha = CONCATENATE('Sales Invoice Line'[Year_Factura],'Sales Invoice Line'[IdCliente])
		lineageTag: c2667109-3fd7-4d08-bea3-f45fc1afe0b0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Id_Documento_Linea = ```
			CONCATENATE('Sales Invoice Line'[Documento],'Sales Invoice Line'[Linea]) 
			```
		lineageTag: 6379f0df-4366-41dc-8fe3-fd5cbd1ca5e7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column COMPROBACION_PRECIO_NETO = ('Sales Invoice Line'[Precio Neto] * 'Sales Invoice Line'[Cantidad]) * 'Sales Invoice Line'[Sentido Cargo/Abono]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 402a34cc-da9a-4fcd-b226-6ae1b57bab32
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column COMPROBACION_TOTALSINIMPUESTOS = 'Sales Invoice Line'[Total Linea Sin Impuesto]*'Sales Invoice Line'[Sentido Cargo/Abono]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 52a07190-bf45-45b5-8975-af9f126b78ce
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column RepresentanteKey = 'Sales Invoice Line'[IdCliente]&'Sales Invoice Line'[IdItem]&'Sales Invoice Line'[Direccion de envio]
		lineageTag: bdc736ad-002c-4dba-a431-a4a55162f2c8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Rep1 = RELATED('Representante Excel'[Código Representante])
		lineageTag: 6d3acce5-e737-4ba6-85f8-65be6065d7ee
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Representante = IF(ISBLANK('Sales Invoice Line'[Rep1]),'Sales Invoice Line'[Comercial 1],'Sales Invoice Line'[Rep1])
		lineageTag: 111185f5-b2d7-4e07-86b8-1dd8c4f4c83a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Inf Codigo Proveedor' = """" &  'Sales Invoice Line'[Codigo Proveedor] & """"
		isHidden
		lineageTag: 9aec7836-7927-4165-b2bc-5355e9e29f5b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Inf Nombre Proveedor' = """" &  'Sales Invoice Line'[Nombre Proveedor] & """"
		isHidden
		lineageTag: 87be0b34-16f1-4d44-ba1c-204a1ac817ce
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: string
		lineageTag: 3681adbf-7238-4bf0-ac7a-37fd8022c333
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column Linea
		dataType: int64
		formatString: 0
		lineageTag: 814f6df2-96d5-4a12-bda4-687b9255a8bd
		summarizeBy: sum
		sourceColumn: Linea

		annotation SummarizationSetBy = Automatic

	column Empresa
		dataType: string
		lineageTag: 24237f00-6437-47a9-b9b3-0ba27fb78473
		summarizeBy: none
		sourceColumn: Empresa

		annotation SummarizationSetBy = Automatic

	column IdCliente
		dataType: string
		lineageTag: ff83052d-6366-49cc-b2ee-19fdd4745093
		summarizeBy: none
		sourceColumn: IdCliente

		annotation SummarizationSetBy = Automatic

	column IdArticulo
		dataType: string
		lineageTag: b99d0a43-850d-4b2c-b885-1e90823d27d4
		summarizeBy: none
		sourceColumn: IdArticulo

		annotation SummarizationSetBy = Automatic

	column Descripcion
		dataType: string
		lineageTag: a04f3bb2-e6b8-463f-a85d-8d7fcad61bad
		summarizeBy: none
		sourceColumn: Descripcion

		annotation SummarizationSetBy = Automatic

	column 'Descripcion 2'
		dataType: string
		lineageTag: 17ca2f85-fe2d-4a3e-af3b-4659027d58b2
		summarizeBy: none
		sourceColumn: Descripcion 2

		annotation SummarizationSetBy = Automatic

	column 'Comercial 1'
		dataType: string
		lineageTag: 768b1f32-b46a-4266-bc4a-a1c8496146e6
		summarizeBy: none
		sourceColumn: Comercial 1

		annotation SummarizationSetBy = Automatic

	column 'Comercial 2'
		dataType: string
		lineageTag: 2946c451-2ab0-47d6-a7c5-b5fcc972dd99
		summarizeBy: none
		sourceColumn: Comercial 2

		annotation SummarizationSetBy = Automatic

	column 'Precio Bruto'
		dataType: double
		lineageTag: 8d7e929f-5f5c-4a77-9e3a-bbce7d84ae21
		summarizeBy: sum
		sourceColumn: Precio Bruto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Motivo Precio'
		dataType: int64
		formatString: 0
		lineageTag: f2ab650a-73ae-482f-a993-7b5c738030e2
		summarizeBy: sum
		sourceColumn: Motivo Precio

		annotation SummarizationSetBy = Automatic

	column 'Precio Neto'
		dataType: double
		lineageTag: cac2d862-291b-46f0-8573-3ac67a947861
		summarizeBy: sum
		sourceColumn: Precio Neto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Precio Neto AI'
		dataType: double
		lineageTag: 5cfc307e-607f-482b-9cfd-fd6ae67bc507
		summarizeBy: sum
		sourceColumn: Precio Neto AI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Precio Neto II'
		dataType: double
		lineageTag: d53903c1-5b7b-46fc-a00e-0384993a7212
		summarizeBy: sum
		sourceColumn: Precio Neto II

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Margen
		dataType: double
		lineageTag: f18ab91c-3ff9-4d22-98c1-21a62b45e286
		summarizeBy: sum
		sourceColumn: Margen

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Precio Coste'
		dataType: double
		lineageTag: a60a0f7d-cc00-454f-8ee9-916183c2d060
		summarizeBy: sum
		sourceColumn: Precio Coste

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Descuento 1'
		dataType: double
		lineageTag: b2d93f1d-e3c6-4ede-9057-317020e808fc
		summarizeBy: sum
		sourceColumn: Descuento 1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Descuento 2'
		dataType: double
		lineageTag: 752ea51f-2974-4c02-8f01-76f76dd54f1c
		summarizeBy: sum
		sourceColumn: Descuento 2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Linea AI'
		dataType: double
		lineageTag: 28380dd7-cf36-4ffc-b746-1c43239c3195
		summarizeBy: sum
		sourceColumn: Total Linea AI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Base Impuesto'
		dataType: double
		lineageTag: f9bddd7d-3fb4-4a78-b559-4d66ec6c39cc
		summarizeBy: sum
		sourceColumn: Base Impuesto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa Impuesto'
		dataType: double
		lineageTag: 4b46cd1b-e28c-4995-a4bd-2314e654d7cc
		summarizeBy: sum
		sourceColumn: Tasa Impuesto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Importe Impuesto'
		dataType: double
		lineageTag: 2361801f-8b57-4ccc-bcfe-55b66ceca2d6
		summarizeBy: sum
		sourceColumn: Importe Impuesto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Linea II'
		dataType: double
		lineageTag: c69e0516-6d59-4e88-8738-1c505b3e3225
		summarizeBy: sum
		sourceColumn: Total Linea II

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cantidad UV'
		dataType: double
		lineageTag: c0fb1a5c-034b-48fb-8416-3a4b5c4cefca
		summarizeBy: sum
		sourceColumn: Cantidad UV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unidad Venta'
		dataType: string
		lineageTag: 3acbd2f5-fd81-409b-8497-cfea4d7e133b
		summarizeBy: none
		sourceColumn: Unidad Venta

		annotation SummarizationSetBy = Automatic

	column 'Coeficiente UV-US'
		dataType: double
		lineageTag: e3779173-2f54-407f-a47c-343afd5bd6cb
		summarizeBy: sum
		sourceColumn: Coeficiente UV-US

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cantidad US'
		dataType: double
		lineageTag: 918a0199-652d-4663-8158-5f7160e9084f
		summarizeBy: sum
		sourceColumn: Cantidad US

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unidad stock'
		dataType: string
		lineageTag: 0a1c7811-200e-4ca8-b6d1-a88193158484
		summarizeBy: none
		sourceColumn: Unidad stock

		annotation SummarizationSetBy = Automatic

	column 'Precio Pedido'
		dataType: double
		lineageTag: f040f8c0-c89d-4468-979f-4867ce969f17
		summarizeBy: sum
		sourceColumn: Precio Pedido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tipo IVA'
		dataType: string
		lineageTag: d3cea0ad-1994-4137-b3e5-4f0a1fb512e2
		summarizeBy: none
		sourceColumn: Tipo IVA

		annotation SummarizationSetBy = Automatic

	column Sentido
		dataType: int64
		formatString: 0
		lineageTag: c14e9221-4204-4958-a2c3-604e8f61fd42
		summarizeBy: sum
		sourceColumn: Sentido

		annotation SummarizationSetBy = Automatic

	column Modulo
		dataType: int64
		formatString: 0
		lineageTag: 7fd1fca7-39f7-40f0-b97a-71a50f752709
		summarizeBy: sum
		sourceColumn: Modulo

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4360c473-a805-40c4-a3f9-5730281d32ba
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Planta stock'
		dataType: string
		lineageTag: f4441833-7fa3-482d-abe5-4c3509da9c33
		summarizeBy: none
		sourceColumn: Planta stock

		annotation SummarizationSetBy = Automatic

	column 'Direccion entrega'
		dataType: string
		lineageTag: 2ceca37c-66f9-47d9-840a-dad301cba543
		summarizeBy: none
		sourceColumn: Direccion entrega

		annotation SummarizationSetBy = Automatic

	hierarchy 'Id_Fecha Hierarchy'
		lineageTag: d9c797ec-734e-48d4-8853-93327aa17ac5

		level Id_Fecha
			lineageTag: 81772be9-e528-42b4-972e-039241661089
			column: Id_Fecha

	partition 'Sales Invoice Line-0c6674fe-a5fc-471c-b110-0db2baba156a' = m
		mode: import
		source = ```
				let
				    CurrentServer = Instancia,
				    CurrentDatabase = BaseDeDatos,
				    CurrentSchema = Esquema,
				    CurrentRows = Registros,
				    CurrentPeriod = Periodo,
				    CurrentCompany = Empresa,
				    Origen = Sql.Database(CurrentServer, CurrentDatabase, [Query="
				
				
				DECLARE @ANO1 VARCHAR(20)
				DECLARE @ANO2 int
				set @ANO1='"& CurrentPeriod &"'
				set @ANO2=(SELECT MIN(PERIODO) FROM (	SELECT YEAR(ACCDAT_0) AS PERIODO,COUNT(*) AS REGISTROS,
														SUM(COUNT(*)) OVER (ORDER BY YEAR(ACCDAT_0) DESC) AS ACUMULADO
														FROM " & CurrentSchema &".SINVOICED as SED left join " & CurrentSchema &".SINVOICE AS SE on SED.NUM_0 = SE.NUM_0
														where SE.ORIMOD_0=5 
														GROUP BY YEAR(ACCDAT_0)
														) A	WHERE ACUMULADO <=" & CurrentRows &")
														
				
				IF @ANO1='Periodo automático'
				
				(
				SELECT 
				SID.NUM_0 'Documento',
				SID.SIDLIN_0 'Linea',
				SID.CPY_0 'Empresa',
				SID.BPCINV_0 'IdCliente',
				SID.ITMREF_0 'IdArticulo',
				SID.ITMDES1_0 'Descripcion',
				SID.ITMDES_0 'Descripcion 2',
				SID.REP1_0 'Comercial 1',
				SID.REP2_0 'Comercial 2',
				SID.GROPRI_0 'Precio Bruto',
				SID.PRIREN_0 'Motivo Precio',
				SID.NETPRI_0 'Precio Neto',
				SID.NETPRINOT_0 'Precio Neto AI',
				SID.NETPRIATI_0 'Precio Neto II',
				SID.PFM_0 'Margen',
				SID.CPRPRI_0 'Precio Coste',
				SID.DISCRGVAL1_0 'Descuento 1',
				SID.DISCRGVAL2_0 'Descuento 2',
				SID.AMTNOTLIN_0 'Total Linea AI',
				SID.BASTAXLIN_0 'Base Impuesto',
				SID.RATTAXLIN_0 'Tasa Impuesto',
				SID.AMTTAXLIN_0 'Importe Impuesto',
				SID.AMTATILIN_0 'Total Linea II',
				SID.QTY_0 'Cantidad UV',
				SID.SAU_0 'Unidad Venta',
				SID.SAUSTUCOE_0 'Coeficiente UV-US',
				SID.QTYSTU_0 'Cantidad US',
				SID.STU_0 'Unidad stock',
				SID.PRIORD_0 'Precio Pedido',
				SID.VAT_0 'Tipo IVA',
				SIH.SNS_0 'Sentido',
				SIH.ORIMOD_0 'Modulo',
				SIH.ACCDAT_0 'Fecha',
				SID.STOFCY_0 'Planta stock', 
				SIV.BPAADD_0 'Direccion entrega'
				
				FROM " & CurrentSchema & ".SINVOICE SIH
				LEFT JOIN " & CurrentSchema & ".SINVOICEV SIV ON SIH.NUM_0 = SIV.NUM_0
				LEFT JOIN " & CurrentSchema & ".SINVOICED SID ON SID.NUM_0 = SIH.NUM_0
				
				WHERE SIH.ORIMOD_0 = 5 AND SIH.INVTYP_0 IN (1,2) AND YEAR(ACCDAT_0)>=@ANO2
				
				
				)
				
				ELSE
				
				(
				SELECT 
				SID.NUM_0 'Documento',
				SID.SIDLIN_0 'Linea',
				SID.CPY_0 'Empresa',
				SID.BPCINV_0 'IdCliente',
				SID.ITMREF_0 'IdArticulo',
				SID.ITMDES1_0 'Descripcion',
				SID.ITMDES_0 'Descripcion 2',
				SID.REP1_0 'Comercial 1',
				SID.REP2_0 'Comercial 2',
				SID.GROPRI_0 'Precio Bruto',
				SID.PRIREN_0 'Motivo Precio',
				SID.NETPRI_0 'Precio Neto',
				SID.NETPRINOT_0 'Precio Neto AI',
				SID.NETPRIATI_0 'Precio Neto II',
				SID.PFM_0 'Margen',
				SID.CPRPRI_0 'Precio Coste',
				SID.DISCRGVAL1_0 'Descuento 1',
				SID.DISCRGVAL2_0 'Descuento 2',
				SID.AMTNOTLIN_0 'Total Linea AI',
				SID.BASTAXLIN_0 'Base Impuesto',
				SID.RATTAXLIN_0 'Tasa Impuesto',
				SID.AMTTAXLIN_0 'Importe Impuesto',
				SID.AMTATILIN_0 'Total Linea II',
				SID.QTY_0 'Cantidad UV',
				SID.SAU_0 'Unidad Venta',
				SID.SAUSTUCOE_0 'Coeficiente UV-US',
				SID.QTYSTU_0 'Cantidad US',
				SID.STU_0 'Unidad stock',
				SID.PRIORD_0 'Precio Pedido',
				SID.VAT_0 'Tipo IVA',
				SIH.SNS_0 'Sentido',
				SIH.ORIMOD_0 'Modulo',
				SIH.ACCDAT_0 'Fecha',
				SID.STOFCY_0 'Planta stock', 
				SIV.BPAADD_0 'Direccion entrega'
				
				FROM " & CurrentSchema & ".SINVOICE SIH
				LEFT JOIN " & CurrentSchema & ".SINVOICEV SIV ON SIH.NUM_0 = SIV.NUM_0
				LEFT JOIN " & CurrentSchema & ".SINVOICED SID ON SID.NUM_0 = SIH.NUM_0
				
				WHERE SIH.ORIMOD_0 = 5 AND SIH.INVTYP_0 IN (1,2) AND YEAR(ACCDAT_0)>=@ANO1
				
				)     
				        
				        
				        "
				                                                          ]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Fecha", type date}})
				in
				    #"Tipo cambiado"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

