table Direccion
	lineageTag: aa57438b-efc9-42f0-97ab-1ec1207a90a3

	column IdDireccion
		dataType: string
		lineageTag: b1f12e0d-57de-40a1-85e0-c61b38a4f684
		summarizeBy: none
		sourceColumn: IdDireccion

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Tipo Entidad'
		dataType: int64
		formatString: 0
		lineageTag: 7b70b012-6769-4c67-b340-1e6bed7b0f84
		summarizeBy: sum
		sourceColumn: Tipo Entidad

		annotation SummarizationSetBy = Automatic

	column Entidad
		dataType: string
		lineageTag: b6238580-9b06-426e-9078-63453ff63d70
		summarizeBy: none
		sourceColumn: Entidad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Direccion
		dataType: string
		lineageTag: b0d09d3b-4b80-4df8-9410-e5e7f0f2a2f1
		summarizeBy: none
		sourceColumn: Direccion

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Descripcion
		dataType: string
		lineageTag: 32622f8a-af22-4481-987c-75a2e03817a7
		summarizeBy: none
		sourceColumn: Descripcion

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Linea Direcion'
		dataType: string
		lineageTag: f677bcc7-55b5-4b2c-97cb-8b8c35c15f27
		summarizeBy: none
		sourceColumn: Linea Direcion

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Linea Direcion 1'
		dataType: string
		lineageTag: 1a163533-00f1-4389-a59e-bab559a171e5
		summarizeBy: none
		sourceColumn: Linea Direcion 1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Linea Direcion 2'
		dataType: string
		lineageTag: 1fda0ccf-fb59-4c2b-89ff-bcb8a5dbd397
		summarizeBy: none
		sourceColumn: Linea Direcion 2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Codigo Postal'
		dataType: string
		lineageTag: 1c54e0e2-906d-4d0b-b9e8-e45a1949b226
		summarizeBy: none
		sourceColumn: Codigo Postal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Ciudad
		dataType: string
		lineageTag: 1e90b38c-2be5-49f5-bb47-69620636fd09
		summarizeBy: none
		sourceColumn: Ciudad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Provincia
		dataType: string
		lineageTag: 74d02e85-ad6a-4769-961a-ac4cb19b2c4f
		summarizeBy: none
		sourceColumn: Provincia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Pais
		dataType: string
		lineageTag: 90504853-3ae1-46ee-a4bd-d94431743135
		summarizeBy: none
		sourceColumn: Pais

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Nombre Pais'
		dataType: string
		lineageTag: d78613e1-2a29-4cf1-a666-57eb706a1769
		summarizeBy: none
		sourceColumn: Nombre Pais

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Telefono 1'
		dataType: string
		lineageTag: 2cd66d12-4abf-43e0-bf9b-93aa18c484a6
		summarizeBy: none
		sourceColumn: Telefono 1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Telefono 2'
		dataType: string
		lineageTag: eb6fd62e-a425-453e-a739-3bdaf54ea196
		summarizeBy: none
		sourceColumn: Telefono 2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Telefono 3'
		dataType: string
		lineageTag: 77e45a20-42d7-446c-8e46-6441ba9c5c8c
		summarizeBy: none
		sourceColumn: Telefono 3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Telefono 4'
		dataType: string
		lineageTag: b74aee86-08b9-4321-a4ec-ceef57abfb59
		summarizeBy: none
		sourceColumn: Telefono 4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Telefono 5'
		dataType: string
		lineageTag: 62822fab-5d00-4395-a22d-1510c47651d3
		summarizeBy: none
		sourceColumn: Telefono 5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Fax
		dataType: string
		lineageTag: 6da97a8e-b2df-4952-841f-5b636927c0ee
		summarizeBy: none
		sourceColumn: Fax

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Movil
		dataType: string
		lineageTag: 8368908e-0fe1-4615-840d-a37cdf5b1ef9
		summarizeBy: none
		sourceColumn: Movil

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Correo 1'
		dataType: string
		lineageTag: b02f9a6c-e83b-46b0-9421-ab8b3d31130c
		summarizeBy: none
		sourceColumn: Correo 1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Correo 2'
		dataType: string
		lineageTag: 45b90562-ae42-4c0a-a1e7-057d844266d4
		summarizeBy: none
		sourceColumn: Correo 2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Correo 3'
		dataType: string
		lineageTag: 1321794d-b299-48b7-a3e5-d0a48778b049
		summarizeBy: none
		sourceColumn: Correo 3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Correo 4'
		dataType: string
		lineageTag: ebe7b4ee-fed8-4c60-ac33-887f2a53a6b5
		summarizeBy: none
		sourceColumn: Correo 4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Correo 5'
		dataType: string
		lineageTag: 2fedd798-67e9-4b0a-9888-6ddd00a16dc8
		summarizeBy: none
		sourceColumn: Correo 5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Sitio Web'
		dataType: string
		lineageTag: 9188f5a0-3833-48e7-a33b-464d237da5f2
		summarizeBy: none
		sourceColumn: Sitio Web

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Provincia Nombre'
		dataType: string
		lineageTag: f894daca-ae3f-44e6-84d0-d136ac33d35f
		summarizeBy: none
		sourceColumn: Provincia Nombre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	hierarchy 'Pais Hierarchy'
		lineageTag: cffea85b-633d-4d65-97ca-036221f06b20

		level 'Nombre Pais'
			lineageTag: ac2185e4-ad0b-4042-b385-9f61231c79c6
			column: 'Nombre Pais'

		level Pais
			lineageTag: 2c926754-06ab-4d61-846d-09847a797d82
			column: Pais

		level Provincia
			lineageTag: f2ce99eb-ea67-4ca4-9427-f2a5c85d78bc
			column: Provincia

		level Ciudad
			lineageTag: 2c6bedba-e5a7-4174-94ad-a00347f02184
			column: Ciudad

	partition Direccion-57074845-8b5f-4a4d-9876-d5f2ef4b0d37 = m
		mode: import
		source = ```
				let
				    CurrentServer = Instancia,
				    CurrentDatabase = BaseDeDatos,
				    CurrentSchema = Esquema,
				    Origen = Sql.Database(CurrentServer, CurrentDatabase, [Query="
				                                                                SELECT  distinct
				                                                                         [BPATYP_0]
				                                                                        ,[BPANUM_0]
				                                                                        ,[BPAADD_0]
				                                                                        ,[BPADES_0]
				                                                                        ,[BPAADDLIG_0]
				                                                                        ,[BPAADDLIG_1]
				                                                                        ,[BPAADDLIG_2]
				                                                                        ,[POSCOD_0]
				                                                                        ,[CTY_0]
				                                                                        ,[SAT_0]
				                                                                        ,ADR.[CRY_0]
				                                                                        ,[CRYNAM_0]
				                                                                        ,[TEL_0]
				                                                                        ,[TEL_1]
				                                                                        ,[TEL_2]
				                                                                        ,[TEL_3]
				                                                                        ,[TEL_4]
				                                                                        ,[FAX_0]
				                                                                        ,[MOB_0]
				                                                                        ,[WEB_0]
				                                                                        ,[WEB_1]
				                                                                        ,[WEB_2]
				                                                                        ,[WEB_3]
				                                                                        ,[WEB_4]
				                                                                        ,[FCYWEB_0]
				                                                                        ,AXX.TEXTE_0
				 FROM " & CurrentSchema & ".BPADDRESS ADR 
				 left join " & CurrentSchema & ".TABSUBDIV TSD on TSD.CRY_0=ADR.CRY_0 and ADR.SAT_0=TSD.COD_0 and TSD.TYP_0 = 3
				 left join " & CurrentSchema & ".ATEXTRA AXX on (AXX.CODFIC_0 = 'TABSUBDIV' and AXX.ZONE_0 = 'INTIT' and AXX.LANGUE_0 = 'SPA' and AXX.IDENT1_0 = TSD.CRYTYP_0 and AXX.IDENT2_0 = TSD.COD_0)"
				                                                          ]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(Origen,{{"BPATYP_0", "Tipo Entidad"}, {"BPANUM_0", "Entidad"}, {"BPAADD_0", "Direccion"}, {"BPADES_0", "Descripcion"}, {"BPAADDLIG_0", "Linea Direcion"}, {"BPAADDLIG_1", "Linea Direcion 1"}, {"BPAADDLIG_2", "Linea Direcion 2"}, {"POSCOD_0", "Codigo Postal"}, {"CTY_0", "Ciudad"}, {"SAT_0", "Provincia"}, {"CRY_0", "Pais"}, {"CRYNAM_0", "Nombre Pais"}, {"TEL_0", "Telefono 1"}, {"TEL_1", "Telefono 2"}, {"TEL_2", "Telefono 3"}, {"TEL_3", "Telefono 4"}, {"TEL_4", "Telefono 5"}, {"FAX_0", "Fax"}, {"MOB_0", "Movil"}, {"WEB_0", "Correo 1"}, {"WEB_1", "Correo 2"}, {"WEB_2", "Correo 3"}, {"WEB_3", "Correo 4"}, {"WEB_4", "Correo 5"}, {"FCYWEB_0", "Sitio Web"},{"TEXTE_0", "Provincia Nombre"}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "IdDireccion", each [Entidad]&"-"&[Direccion]),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Personalizada agregada",{"IdDireccion", "Tipo Entidad", "Entidad", "Direccion", "Descripcion", "Linea Direcion", "Linea Direcion 1", "Linea Direcion 2", "Codigo Postal", "Ciudad", "Provincia", "Pais", "Nombre Pais", "Telefono 1", "Telefono 2", "Telefono 3", "Telefono 4", "Telefono 5", "Fax", "Movil", "Correo 1", "Correo 2", "Correo 3", "Correo 4", "Correo 5", "Sitio Web"}),
				    #"Removed Duplicates" = Table.Distinct(#"Columnas reordenadas", {"IdDireccion"})
				in
				    #"Removed Duplicates"
				```

	annotation PBI_ResultType = Table

