table Items
	lineageTag: f3514044-18e3-4e8f-842d-93188140c17d

	column IdItem
		dataType: string
		lineageTag: b3e333f2-7eae-4536-88fa-9411518c22d3
		summarizeBy: none
		sourceColumn: IdItem

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Sociedad
		dataType: string
		lineageTag: c51014fa-0eee-427e-8e79-e284c38077c3
		summarizeBy: none
		sourceColumn: Sociedad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column IdCategoria
		dataType: string
		lineageTag: a3fe3e9a-bf6d-4a7b-a1f6-456bd43cf239
		summarizeBy: none
		sourceColumn: IdCategoria

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column CATEGORIA
		dataType: string
		lineageTag: 6b644aaf-e45e-4b23-9d63-bcf195b4c5eb
		summarizeBy: none
		sourceColumn: CATEGORIA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Codigo Contable'
		dataType: string
		lineageTag: afe42cea-0f48-42be-b9ec-f305a976f026
		summarizeBy: none
		sourceColumn: Codigo Contable

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Descripcion 1'
		dataType: string
		lineageTag: 06c944f2-7538-4a70-8db8-4bccf8189127
		summarizeBy: none
		sourceColumn: Descripcion 1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Descripcion 2'
		dataType: string
		lineageTag: 71b32365-68f6-49af-9300-86c1f2df87d4
		summarizeBy: none
		sourceColumn: Descripcion 2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Descripcion 3'
		dataType: string
		lineageTag: ab46744f-bbc8-4034-bb3a-2662b9dbfe4e
		summarizeBy: none
		sourceColumn: Descripcion 3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Unidad
		dataType: string
		lineageTag: ccd1a4e2-2126-428f-9b9e-89c5ae31a97e
		summarizeBy: none
		sourceColumn: Unidad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Nivel Impuesto'
		dataType: string
		lineageTag: 1a6f83af-ea31-4ca8-b01e-b238d5b9d00a
		summarizeBy: none
		sourceColumn: Nivel Impuesto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Comprador
		dataType: string
		lineageTag: 11dffeef-180c-4d5e-9c31-a4c735194df0
		summarizeBy: none
		sourceColumn: Comprador

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Precio Base'
		dataType: double
		lineageTag: 441e6d03-0b99-463b-b9cd-2778d5c355fa
		summarizeBy: none
		sourceColumn: Precio Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Coef Gastos Entrega'
		dataType: double
		lineageTag: 376aaaa9-eeab-4cb7-9463-c87964912370
		summarizeBy: none
		sourceColumn: Coef Gastos Entrega

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Coste Fijo Unitario'
		dataType: double
		lineageTag: 6f793a00-2b16-4d56-9d00-a522ba6e96e5
		summarizeBy: none
		sourceColumn: Coste Fijo Unitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Linea Negocio'
		dataType: string
		lineageTag: 50cef04a-6708-4753-904f-94e377e19406
		summarizeBy: none
		sourceColumn: Linea Negocio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Codigo Business Unit Analisis'
		dataType: string
		lineageTag: b4b23a21-71de-40c6-b34c-d470126bcdd4
		summarizeBy: none
		sourceColumn: Codigo Business Unit Analisis

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Codigo Familia Analisis'
		dataType: string
		lineageTag: b5ada66c-b953-4dec-b807-85c419a81564
		summarizeBy: none
		sourceColumn: Codigo Familia Analisis

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Business Unit'
		dataType: string
		lineageTag: 4618bf89-9703-460a-97e9-2b25c1b1158a
		summarizeBy: none
		sourceColumn: Business Unit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Familia
		dataType: string
		lineageTag: a4638747-4e66-4472-aba9-1acfaff596f2
		summarizeBy: none
		sourceColumn: Familia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Cantidad Minima'
		dataType: double
		lineageTag: 1c425f63-e469-4a9c-97a9-a4a1d4807d8d
		summarizeBy: none
		sourceColumn: Cantidad Minima

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cantidad Máxima'
		dataType: double
		lineageTag: 83114eac-f5a3-4db1-b86e-ccf2956a1137
		summarizeBy: none
		sourceColumn: Cantidad Máxima

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Margen Minimo'
		dataType: double
		lineageTag: 25aec526-ae7b-4fe3-a265-2f674300e4e6
		summarizeBy: none
		sourceColumn: Margen Minimo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Precio Minimo'
		dataType: double
		lineageTag: c62c553c-158e-4fbd-9cfe-c8062b6ee1fd
		summarizeBy: none
		sourceColumn: Precio Minimo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Precio Teorico'
		dataType: double
		lineageTag: c070fb54-31eb-4208-8ef9-218c4aa79035
		summarizeBy: none
		sourceColumn: Precio Teorico

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Precio Base Ventas'
		dataType: double
		lineageTag: ed885bae-2f2f-43bd-b436-04cd670683a0
		summarizeBy: none
		sourceColumn: Precio Base Ventas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IdArticulo_descripcion = CONCATENATE('Items'[IdItem],CONCATENATE(" - ",'Items'[Descripcion 1]))
		lineageTag: d0e5980a-e891-4a01-a797-6a3cd38d7bfe
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Items-b82692f0-a25b-4f0e-8615-4429edd05937 = m
		mode: import
		source =
				let
				    CurrentServer = Instancia,
				    CurrentDatabase = BaseDeDatos,
				    CurrentSchema = Esquema,
				    Origen = Sql.Database(CurrentServer, CurrentDatabase, [Query="
				                                                                SELECT   ITM.[ITMREF_0] AS IdItem
				                                                                        ,ITM.[CPY_0] AS Sociedad
				                                                                        ,ITM.[TCLCOD_0] AS IdCategoria
				                                                                        ,TXCAT.TEXTE_0 AS CATEGORIA
				                                                                        ,ITM.[ACCCOD_0] AS 'Codigo Contable'
				                                                                        ,ITM.[ITMDES1_0] AS 'Descripcion 1'
				                                                                        ,ITM.[ITMDES2_0] AS 'Descripcion 2'
				                                                                        ,ITM.[ITMDES3_0] AS 'Descripcion 3'
				                                                                        ,ITM.[STU_0] AS Unidad
				                                                                        ,ITM.[VACITM_0] AS 'Nivel Impuesto'
				                                                                        ,ITM.[BUY_0] AS Comprador
				                                                                        ,ITM.[PURBASPRI_0] AS 'Precio Base'
				                                                                        ,ITM.[CPRCOE_0] AS 'Coef Gastos Entrega'
				                                                                        ,ITM.[CPRAMT_0] AS 'Coste Fijo Unitario'
				                                                                        ,ITM.[CCE_0] AS 'Linea Negocio'
				                                                                        ,ITM.TSICOD_0 AS 'Codigo Famlia Analisis'
				                                                                        ,ITM.TSICOD_1 AS 'Codigo Subfamilia Analisis'
				                                                                        ,TXT.TEXTE_0 AS Familia
				                                                                        ,TXT2.TEXTE_0 AS Subfamilia
				                                                                        ,ITMS.[MINQTY_0] AS 'Cantidad Minima'
				                                                                        ,ITMS.[MAXQTY_0] AS 'Cantidad Máxima'
				                                                                        ,ITMS.[MINPFM_0] AS 'Margen Minimo'
				                                                                        ,ITMS.[MINPRI_0] AS 'Precio Minimo'
				                                                                        ,ITMS.[THEPRI_0] AS 'Precio Teorico'
				                                                                        ,ITMS.[BASPRI_0] AS 'Precio Base Ventas'
				                                                                    FROM " & CurrentSchema & ".ITMMASTER AS ITM
				                                                                    LEFT JOIN " & CurrentSchema & ".[ITMSALES] AS ITMS
				                                                                    ON ITM.ITMREF_0 = ITMS.ITMREF_0
				                                                                    LEFT JOIN " & CurrentSchema & ".ATEXTRA as TXT
				                                                                    on ITM.TSICOD_0 = TXT.IDENT2_0  AND CODFIC_0 = 'ATABDIV' AND ZONE_0 = 'LNGDES' AND IDENT1_0 = '20' AND LANGUE_0 = 'SPA'
				                                                                    LEFT JOIN " & CurrentSchema & ".ATEXTRA as TXT2
				                                                                    on ITM.TSICOD_1 = TXT2.IDENT2_0 AND TXT2.CODFIC_0 = 'ATABDIV' AND TXT2.ZONE_0 = 'LNGDES' AND TXT2.IDENT1_0 = '21' AND TXT2.LANGUE_0 = 'SPA'
				                                                                    LEFT JOIN " & CurrentSchema & ".ATEXTRA AS TXCAT
				                                                                    ON ITM.TCLCOD_0 = TXCAT.IDENT1_0 AND TXCAT.CODFIC_0 = 'ITMCATEG' AND TXCAT.ZONE_0 = 'TCLAXX' AND TXCAT.LANGUE_0 = 'SPA'"
				                                                          ]),
				    #"Renamed Columns" = Table.RenameColumns(Origen,{{"Familia", "Business Unit"}, {"Codigo Famlia Analisis", "Codigo Business Unit Analisis"}, {"Codigo Subfamilia Analisis", "Codigo Familia Analisis"}, {"Subfamilia", "Familia"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

